# Generated by Django 6.0 on 2026-02-04 05:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0032_remove_workexperience_gap_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certification_name', models.CharField(max_length=255)),
                ('issuing_organization', models.CharField(max_length=255)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_lifetime', models.BooleanField(default=False)),
                ('certificate_number', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(blank=True, null=True, upload_to='certifications/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='candidates.candidate')),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
    ]
