# Generated by Django 6.0 on 2026-02-04 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0033_add_certification_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='certificate_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
