# Generated by Django 6.0 on 2026-02-04 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0034_add_certificate_url_to_certification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='certificate_number',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='certificate_url',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='is_lifetime',
        ),
    ]
