# Generated by Django 4.2.27 on 2026-03-31 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0035_remove_certification_extra_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='work_experience_details',
        ),
    ]
