# Generated by Django 6.0 on 2025-12-31 08:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hrprofile',
            name='credits_balance',
        ),
        migrations.AddField(
            model_name='hrprofile',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        # migrations.AlterField(
        #     model_name='hrprofile',
        #     name='id',
        #     field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        # ),
    ]
