# Generated by Django 6.0 on 2026-02-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0006_company_company_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrprofile',
            name='is_profile_completed',
            field=models.BooleanField(default=False, help_text='Indicates if recruiter has completed profile setup'),
        ),
        migrations.AddField(
            model_name='hrprofile',
            name='profile_step',
            field=models.IntegerField(default=0, help_text='Profile setup step: 0=not started, 1=basic info filled, 2=complete'),
        ),
    ]
