# Generated by Django 4.2.27 on 2026-04-05 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0007_hrprofile_is_profile_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrprofile',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
