# Generated by Django 4.2.27 on 2026-02-04 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_dashboardcontent_main_heading'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboardcontent',
            options={'ordering': ['screen'], 'verbose_name': 'Dashboard Text Message', 'verbose_name_plural': 'Dashboard Text Messages'},
        ),
    ]
