# Generated by Django 6.0 on 2026-01-17 09:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('screen', models.CharField(choices=[('CANDIDATE_DASHBOARD', 'Candidate Dashboard'), ('HR_DASHBOARD', 'HR Dashboard')], help_text='Which dashboard screen this content is for', max_length=50, unique=True)),
                ('main_heading', models.CharField(default='Ready to take the\nnext step?', help_text='Main heading text (use \\n for line breaks)', max_length=200)),
                ('subheading', models.CharField(blank=True, help_text='Optional subheading below main heading', max_length=300, null=True)),
                ('welcome_prefix', models.CharField(default='Hello 👋', help_text='Greeting text shown in header', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dashboard Content',
                'verbose_name_plural': 'Dashboard Contents',
                'ordering': ['screen'],
            },
        ),
    ]
