# Generated by Django 6.0 on 2026-01-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_text_message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardcontent',
            name='main_heading',
            field=models.CharField(default='Ready to take the\\nnext step?', help_text='Main heading text (use \\n for line breaks)', max_length=200),
        ),
    ]
