# Generated by Django 6.0 on 2026-02-04 16:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0035_remove_certification_extra_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_points_per_year', models.IntegerField(default=10, help_text='Points awarded per year of experience', validators=[django.core.validators.MinValueValidator(0)])),
                ('max_experience_points', models.IntegerField(default=100, help_text='Maximum points from experience', validators=[django.core.validators.MinValueValidator(0)])),
                ('points_10th', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('points_12th', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('points_diploma', models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('points_bachelors', models.IntegerField(default=25, validators=[django.core.validators.MinValueValidator(0)])),
                ('points_masters', models.IntegerField(default=40, validators=[django.core.validators.MinValueValidator(0)])),
                ('points_phd', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0)])),
                ('points_per_certification', models.IntegerField(default=15, help_text='Points per certification', validators=[django.core.validators.MinValueValidator(0)])),
                ('max_certification_points', models.IntegerField(default=75, help_text='Maximum points from certifications', validators=[django.core.validators.MinValueValidator(0)])),
                ('points_per_skill', models.IntegerField(default=3, help_text='Points per skill', validators=[django.core.validators.MinValueValidator(0)])),
                ('max_skills_points', models.IntegerField(default=50, help_text='Maximum points from skills', validators=[django.core.validators.MinValueValidator(0)])),
                ('points_resume_uploaded', models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('points_video_uploaded', models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('points_profile_image_uploaded', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('points_career_objective_filled', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('points_all_steps_completed', models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('points_immediate_joining', models.IntegerField(default=10, help_text='Bonus for immediate joining availability', validators=[django.core.validators.MinValueValidator(0)])),
                ('points_willing_to_relocate', models.IntegerField(default=10, help_text='Bonus for willing to relocate', validators=[django.core.validators.MinValueValidator(0)])),
                ('points_verified_profile', models.IntegerField(default=30, help_text='Bonus for admin-verified profile', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True, help_text='Only one configuration can be active at a time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ranking Configuration',
                'verbose_name_plural': 'Ranking Configurations',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateRank',
            fields=[
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='rank', serialize=False, to='candidates.candidate')),
                ('total_score', models.IntegerField(default=0, help_text='Sum of all score components', validators=[django.core.validators.MinValueValidator(0)])),
                ('experience_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('education_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('certification_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('skills_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('profile_completeness_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('availability_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('verification_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('rank_position', models.IntegerField(blank=True, help_text='Position among all candidates (1st, 2nd, 3rd...)', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('price_tier', models.CharField(choices=[('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum'), ('DIAMOND', 'Diamond')], default='BRONZE', help_text='Tier determining credit cost', max_length=20)),
                ('credits_required', models.IntegerField(default=5, help_text='Credits needed to unlock this candidate', validators=[django.core.validators.MinValueValidator(1)])),
                ('last_calculated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Candidate Rank',
                'verbose_name_plural': 'Candidate Rankings',
                'ordering': ['-total_score'],
                'indexes': [models.Index(fields=['-total_score'], name='ranking_can_total_s_699e4a_idx'), models.Index(fields=['price_tier'], name='ranking_can_price_t_d759cd_idx')],
            },
        ),
        migrations.CreateModel(
            name='RankingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('rank_position', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('price_tier', models.CharField(max_length=20)),
                ('credits_required', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_history', to='candidates.candidate')),
            ],
            options={
                'verbose_name': 'Ranking History',
                'verbose_name_plural': 'Ranking History',
                'ordering': ['-calculated_at'],
                'indexes': [models.Index(fields=['candidate', '-calculated_at'], name='ranking_ran_candida_316cda_idx')],
            },
        ),
    ]
