# Generated by Django 6.0 on 2026-02-04 16:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankingconfig',
            name='credits_bronze',
            field=models.IntegerField(default=10, help_text='Credits for BRONZE tier (0-39 points)', validators=[django.core.validators.MinValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='rankingconfig',
            name='credits_diamond',
            field=models.IntegerField(default=20, help_text='Credits for DIAMOND tier (90-100 points)', validators=[django.core.validators.MinValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='rankingconfig',
            name='credits_gold',
            field=models.IntegerField(default=15, help_text='Credits for GOLD tier (60-79 points)', validators=[django.core.validators.MinValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='rankingconfig',
            name='credits_platinum',
            field=models.IntegerField(default=18, help_text='Credits for PLATINUM tier (80-89 points)', validators=[django.core.validators.MinValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='rankingconfig',
            name='credits_silver',
            field=models.IntegerField(default=12, help_text='Credits for SILVER tier (40-59 points)', validators=[django.core.validators.MinValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='rankingconfig',
            name='experience_points_per_year',
            field=models.IntegerField(default=2, help_text='Points awarded per year of experience', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='rankingconfig',
            name='max_certification_points',
            field=models.IntegerField(default=20, help_text='Maximum points from certifications', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='rankingconfig',
            name='max_experience_points',
            field=models.IntegerField(default=20, help_text='Maximum points from experience', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='rankingconfig',
            name='max_skills_points',
            field=models.IntegerField(default=10, help_text='Maximum points from skills', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='rankingconfig',
            name='points_10th',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='rankingconfig',
            name='points_12th',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='rankingconfig',
            name='points_all_steps_completed',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='rankingconfig',
            name='points_bachelors',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='rankingconfig',
            name='points_career_objective_filled',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='rankingconfig',
            name='points_diploma',
            field=models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='rankingconfig',
            name='points_immediate_joining',
            field=models.IntegerField(default=3, help_text='Bonus for immediate joining availability', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='rankingconfig',
            name='points_masters',
            field=models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='rankingconfig',
            name='points_per_certification',
            field=models.IntegerField(default=5, help_text='Points per certification', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='rankingconfig',
            name='points_per_skill',
            field=models.IntegerField(default=1, help_text='Points per skill', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='rankingconfig',
            name='points_phd',
            field=models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='rankingconfig',
            name='points_profile_image_uploaded',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='rankingconfig',
            name='points_resume_uploaded',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='rankingconfig',
            name='points_verified_profile',
            field=models.IntegerField(default=10, help_text='Bonus for admin-verified profile', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='rankingconfig',
            name='points_video_uploaded',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='rankingconfig',
            name='points_willing_to_relocate',
            field=models.IntegerField(default=3, help_text='Bonus for willing to relocate', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
