# Generated by Django 6.0 on 2026-02-05 05:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0002_rankingconfig_credits_bronze_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsCreditMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_threshold', models.IntegerField(help_text='Minimum points required for this credit tier', unique=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('credits_required', models.IntegerField(help_text='Credits required to unlock candidate at this points level', validators=[django.core.validators.MinValueValidator(10)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Points-Credits Mapping',
                'verbose_name_plural': 'Points-Credits Mappings',
                'ordering': ['points_threshold'],
            },
        ),
        migrations.RemoveIndex(
            model_name='candidaterank',
            name='ranking_can_price_t_d759cd_idx',
        ),
        migrations.RemoveField(
            model_name='rankingconfig',
            name='credits_bronze',
        ),
        migrations.RemoveField(
            model_name='rankingconfig',
            name='credits_diamond',
        ),
        migrations.RemoveField(
            model_name='rankingconfig',
            name='credits_gold',
        ),
        migrations.RemoveField(
            model_name='rankingconfig',
            name='credits_platinum',
        ),
        migrations.RemoveField(
            model_name='rankingconfig',
            name='credits_silver',
        ),
        migrations.RemoveField(
            model_name='rankinghistory',
            name='price_tier',
        ),
        migrations.RemoveField(
            model_name='rankinghistory',
            name='rank_position',
        ),
        migrations.AlterField(
            model_name='candidaterank',
            name='credits_required',
            field=models.IntegerField(default=10, help_text='Credits needed to unlock this candidate', validators=[django.core.validators.MinValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='rankinghistory',
            name='credits_required',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(10)]),
        ),
        migrations.RemoveField(
            model_name='candidaterank',
            name='price_tier',
        ),
        migrations.RemoveField(
            model_name='candidaterank',
            name='rank_position',
        ),
    ]
