# Generated by Django 4.2.27 on 2026-02-06 15:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0003_pointscreditmapping_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankingconfig',
            name='points_immediate_joining',
            field=models.DecimalField(decimal_places=2, default=3.0, help_text='Bonus for immediate joining availability', max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='rankingconfig',
            name='points_willing_to_relocate',
            field=models.DecimalField(decimal_places=2, default=3.0, help_text='Bonus for willing to relocate', max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
