# Generated by Django 4.2.27 on 2026-04-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruiterBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=200, null=True)),
                ('subheading', models.CharField(blank=True, max_length=300, null=True)),
                ('image', models.ImageField(upload_to='recruiter_banners/')),
                ('height', models.PositiveIntegerField(default=250, help_text='Banner height in pixels')),
                ('heading_font_size', models.PositiveIntegerField(default=18, help_text='Font size in sp')),
                ('heading_color', models.CharField(default='#FFFFFF', help_text='Hex color code (e.g., #FFFFFF)', max_length=9)),
                ('heading_font_weight', models.CharField(choices=[('300', 'Light'), ('400', 'Regular'), ('500', 'Medium'), ('600', 'Semi Bold'), ('700', 'Bold')], default='600', max_length=3)),
                ('subheading_font_size', models.PositiveIntegerField(default=14, help_text='Font size in sp')),
                ('subheading_color', models.CharField(default='#FFFFFF', help_text='Hex color code (e.g., #FFFFFF)', max_length=9)),
                ('subheading_font_weight', models.CharField(choices=[('300', 'Light'), ('400', 'Regular'), ('500', 'Medium'), ('600', 'Semi Bold'), ('700', 'Bold')], default='400', max_length=3)),
                ('text_align', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Recruiter Banner',
                'verbose_name_plural': 'Recruiter Banners',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['-created_at'], 'verbose_name': 'Candidate Banner', 'verbose_name_plural': 'Candidate Banners'},
        ),
        migrations.AddField(
            model_name='banner',
            name='border_radius',
            field=models.PositiveIntegerField(default=16, help_text='Banner border radius in pixels'),
        ),
        migrations.AddField(
            model_name='banner',
            name='button_bg_color',
            field=models.CharField(default='#FFFFFF', help_text='Button background color', max_length=9),
        ),
        migrations.AddField(
            model_name='banner',
            name='button_border_radius',
            field=models.PositiveIntegerField(default=20, help_text='Button border radius in pixels'),
        ),
        migrations.AddField(
            model_name='banner',
            name='button_font_size',
            field=models.PositiveIntegerField(default=13, help_text='Button font size in sp'),
        ),
        migrations.AddField(
            model_name='banner',
            name='button_font_weight',
            field=models.CharField(choices=[('300', 'Light'), ('400', 'Regular'), ('500', 'Medium'), ('600', 'Semi Bold'), ('700', 'Bold')], default='600', max_length=3),
        ),
        migrations.AddField(
            model_name='banner',
            name='button_padding_horizontal',
            field=models.PositiveIntegerField(default=20, help_text='Button horizontal padding'),
        ),
        migrations.AddField(
            model_name='banner',
            name='button_padding_vertical',
            field=models.PositiveIntegerField(default=10, help_text='Button vertical padding'),
        ),
        migrations.AddField(
            model_name='banner',
            name='button_text_color',
            field=models.CharField(default='#000000', help_text='Button text color', max_length=9),
        ),
        migrations.AddField(
            model_name='banner',
            name='content_alignment',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', help_text='Content alignment', max_length=10),
        ),
        migrations.AddField(
            model_name='banner',
            name='content_padding',
            field=models.PositiveIntegerField(default=20, help_text='Content padding in pixels'),
        ),
        migrations.AddField(
            model_name='banner',
            name='gradient_end_color',
            field=models.CharField(default='#000000', help_text='Gradient end color', max_length=9),
        ),
        migrations.AddField(
            model_name='banner',
            name='gradient_end_opacity',
            field=models.DecimalField(decimal_places=2, default=0.15, help_text='Opacity 0.0 to 1.0', max_digits=3),
        ),
        migrations.AddField(
            model_name='banner',
            name='gradient_start_color',
            field=models.CharField(default='#000000', help_text='Gradient start color', max_length=9),
        ),
        migrations.AddField(
            model_name='banner',
            name='gradient_start_opacity',
            field=models.DecimalField(decimal_places=2, default=0.7, help_text='Opacity 0.0 to 1.0', max_digits=3),
        ),
        migrations.AddField(
            model_name='banner',
            name='height',
            field=models.PositiveIntegerField(default=170, help_text='Banner height in pixels'),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_color',
            field=models.CharField(default='#FFFFFF', help_text='Hex color code (e.g., #FFFFFF)', max_length=9),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_font_size',
            field=models.PositiveIntegerField(default=15, help_text='Title font size in sp'),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_font_weight',
            field=models.CharField(choices=[('300', 'Light'), ('400', 'Regular'), ('500', 'Medium'), ('600', 'Semi Bold'), ('700', 'Bold')], default='600', max_length=3),
        ),
        migrations.AddField(
            model_name='banner',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='button_text',
            field=models.CharField(blank=True, help_text='Button text (optional)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(blank=True, help_text='Banner heading (optional)', max_length=200, null=True),
        ),
    ]
