# Generated by Django 4.2.27 on 2026-04-05 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_recruiterbanner_alter_banner_options_and_more'),
        ('banners', '0005_alter_banner_options_banner_border_radius_and_more'),
    ]

    operations = [
    ]
